#Build the Maven project
FROM winamd64/openjdk as builder
COPY . /usr/src/app
WORKDIR /usr/src/app
RUN ./mvnw clean package

#Build the Tomcat container
FROM winamd64/openjdk

# Copy fhirFilter war file to webapps.
COPY --from=builder /usr/src/app/target/pacer-index-api.jar pacer-index-api.jar
EXPOSE 8080

ENTRYPOINT ["java","-jar","/pacer-index-api.jar"]
